name: Validate JSON
on: [pull_request]

jobs:
  test-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_JSONS: translations/**.json, test.json
